
services:
  db:
    image: postgres:17.6
    restart: always
    ports:
      - '5436:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: bookstore_db
    volumes:
      - ./postgres:/var/lib/postgresql/data