
services:
  db:
    image: postgres:17.6
    restart: always
    ports:
      - '${PORT_DB}:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    container_name: bookstore_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  # API NestJS
  api:
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE}
      - UPLOAD_PATH=./uploads
      - HOST_API=http://localhost:5000
      - FILES_API=http://localhost:5000/files
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads
      - ./static:/app/static
    container_name: cmpc-api

volumes:
  postgres_data:
    driver: local

networks:
  bookstore_network:
    driver: bridge