
services:
  db:
    image: postgres:17.6
    restart: always
    ports:
      - '${PORT_DB}:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: trust
    container_name: bookstore_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  